### ISSUE TITLE
Version without color enhancements

### ISSUE THREAD

**Issue by robtedes123** [qbism/Quake2-colored-refsoft#1]
Hey this is great, any chance you might put up a dll without any extra color, widescreen or other enhancements. The DDraw error I was getting from 3,24 was a pain and this dll fixes it. I'm really just trying to play it like how it looked in 1997

**Comment by qbism** [comment]
Unlikely, but try setting r_lightsaturation to 0 or 0.1. 
The q2dos project on bitbucket has a windows build with ref_soft.  Might be worth trying.
